name: Sync Image to Aliyun  Example
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Git pull
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1
 
    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: crpi-ixmppstjb24p0kx8.cn-guangzhou.personal.cr.aliyuncs.com/docker_copy_2024_09_27/rancher #注意这里
        username: 18142600980
        password: qjj19971111
        logout: false
        
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
         skopeo copy docker://rancher/rancher:latest docker://crpi-ixmppstjb24p0kx8.cn-guangzhou.personal.cr.aliyuncs.com/docker_copy_2024_09_27/rancher:latest
      # 使用 skopeo 工具将镜像同步到阿里云个人仓库中，使用时请自行源和目标修改仓库名称和镜像名称
