name: Download Image from Alibaba Cloud  
  
on:  
  push:  
    branches: [ main ]  

jobs:  
  download-image:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout  
        uses: actions/checkout@v3  
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          registry: crpi-ixmppstjb24p0kx8.cn-guangzhou.personal.cr.aliyuncs.com/docker_copy_2024_09_27/docker_ui #注意这里
          username: 18142600980
          password: qjj19971111
          logout: false
          
      - name: Pull Image from ACR  
        run: |  
          docker pull crpi-ixmppstjb24p0kx8.cn-guangzhou.personal.cr.aliyuncs.com/docker_copy_2024_09_27/docker_ui:last 
   
      - name: Compress the TAR files
        run: tar -czf arm64-images.tar.gz *-arm64.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-images-tar
          path: arm64-images.tar.gz
          retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

      - name: Clean up intermediate files
        run: |
          rm *-arm64.tar
