name: Download Image from Alibaba Cloud  
  
on:  
  push:  
    branches: [ main ]  

jobs:  
  download-image:  
    runs-on: ubuntu-latest  
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: crpi-ixmppstjb24p0kx8.cn-guangzhou.personal.cr.aliyuncs.com/docker_copy_2024_09_27/docker_ui #注意这里
        username: 18142600980
        password: qjj19971111
        logout: false
          
    - name: Pull Docker Images and Package
      run: |
          docker pull crpi-ixmppstjb24p0kx8.cn-guangzhou.personal.cr.aliyuncs.com/docker_copy_2024_09_27/docker_ui:last 
          docker save crpi-ixmppstjb24p0kx8.cn-guangzhou.personal.cr.aliyuncs.com/docker_copy_2024_09_27/docker_ui:last -o docker_ui-arm64.tar 
  

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker_ui-arm64.tar
        path: docker_ui-arm64.tar
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天


